import type { MetadataRoute } from 'next';
import { site } from '@/lib/site';

/**
 * Crawl rules.
 *
 * ── Why /api/og is explicitly allowed ─────────────────────────────────────
 * Every Open Graph and Twitter card image on this site is generated by
 * `/api/og`. A blanket `Disallow: /api/` therefore blocked the site's own
 * social preview images: Twitterbot and several link-preview fetchers honour
 * robots.txt before fetching an image, so shared links rendered without a
 * card. The allow rule is listed BEFORE the disallow because that is the
 * order most crawlers read, and the more specific path wins regardless.
 *
 * Everything else under /api stays closed — /api/contact is a write endpoint
 * with no business being crawled.
 */

const RULE = {
  allow: ['/', '/api/og'],
  disallow: ['/api/'],
} as const;

const AI_CRAWLERS = [
  'GPTBot',
  'ChatGPT-User',
  'OAI-SearchBot',
  'ClaudeBot',
  'anthropic-ai',
  'PerplexityBot',
  'Google-Extended',
  'GoogleOther',
  'CCBot',
  'Bytespider',
  'Amazonbot',
  'Applebot-Extended',
  'DuckAssistBot',
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: '*', allow: [...RULE.allow], disallow: [...RULE.disallow] },
      // Explicitly allow the major answer-engine and AI search crawlers while
      // keeping private/server endpoints out of the crawl surface.
      ...AI_CRAWLERS.map((userAgent) => ({
        userAgent,
        allow: [...RULE.allow],
        disallow: [...RULE.disallow],
      })),
    ],
    sitemap: `${site.url}/sitemap.xml`,
    host: site.url,
  };
}
